# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ''

fail_fast: true

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    - id: pyupgrade

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-merge-conflict     # Check for files that contain merge conflict strings.
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: [--profile, black]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args:
      - --in-place
      - --remove-all-unused-imports
      - --remove-unused-variables
      - --recursive

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
      args:
      - --in-place
      - --recursive
      - --max-line-length=120

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
      - --ignore=E501,W503

  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      additional_dependencies: [click==8.0.4]
